---
nginx_server_name: '{{inventory_hostname}}'
nginx_ssl_dest_dir: /etc/ssl
nginx_strong_dh_group: true 
nginx_use_letsencrypt: false

letsencrypt_dir: "/etc/letsencrypt/live/{{inventory_hostname}}"
letsencrypt_cert_filename: fullchain.pem
letsencrypt_privkey_filename: privkey.pem
