---
- name: Add ssh agent line to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep += "SSH_AUTH_SOCK"
  when: ssh_forward_agent is defined and ssh_forward_agent
  tags: git

- name: Delete Git content & directory
  file:
    state: absent
    path: '{{project_path}}'
  tags: git

- name: Setup the Git repo
  environment:
    TMPDIR: "/var/tmp"
  git: 
    repo: '{{git_repo}}'
    version: '{{git_branch}}'
    dest: '{{project_path}}'
    accept_hostkey: yes
  when: setup_git_repo is defined and setup_git_repo
  notify: restart application
  tags: git

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: '{{project_path}}'
  tags: git
  changed_when: false
