---
- name: install Certbot for letsencrypt
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    update_cache: '{{update_apt_cache}}'
    state: present
  tags: packages

- name: Check if Nginx service exists
  stat: 
    path: /etc/init.d/nginx
  register: nginx_status

- name: check Nginx service is stopped
  service: 
    name: nginx
    state: stopped
  when: nginx_status.stat.exists

- name: Install certbot and generate new cert
  command: '{{certbot_binary}} certonly --noninteractive --agree-tos --standalone --email {{certbot_admin_email}} -d {{inventory_hostname}}'
  args:
    creates: '{{certbot_certs_dir}}'

- name: check Nginx service is started
  service: 
    name: nginx
    state: started
  when: nginx_status.stat.exists

- name: Setup a cron job to auto-renew the certificate
  cron: 
    name: "daily auto renew cert"
    special_time: daily
    job: '{{certbot_binary}} renew --standalone --no-self-upgrade --pre-hook \"service nginx stop\" --post-hook \"service nginx start\" --quiet"
    state: present
  when: certbot_auto_renew
